version: 0.2
env: 
  parameter-store:
    CODEARTIFACT_AUTH_TOKEN: codeartifact-token
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - cp ./settings.xml /root/.m2/settings.xml
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain vpropath --domain-owner 598189530267 --region us-east-1 --query authorizationToken --output text`
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y jq checkstyle maven
  build:
    commands:
      - mvn clean install -DskipTests
artifacts:
  files:
     - target/**/*.war
  discard-paths: yes
